### PR TITLE
Added default .gitignore for Visual Studio

### LINKED ISSUE #12: Remove binaries from repository
Add a .gitignore file to the repository so the binaries don't clutter up the diffs and get copied from branch to branch all over the history of the repository. Having them in the repository drastically increases the size of the repo.

Will follow up with a PR.

### PR DESCRIPTION
**Pull request by rubberduck203**
Partially resolves #12.
The binaries still need to be stripped out of both Master and Dev branches

### CODE REVIEW

**Comment by rubberduck203** [comment]
Resolves #12 
At least, I think I got all of the binaries.

**Comment by ChrisNelsonPE** [comment]
Also see #20

**Comment by rubberduck203** [comment]
At a glance, it looks like #20 did a more thorough job than my quick go at it. @ChrisNelsonPE is this PR of mine obsolete, or still needed in addition to yours?

**Comment by ChrisNelsonPE** [comment]
@ckuhn203 I didn't refer to yours when creating mine so it stands alone.  I'm not sure if there is overlap. I guess you could try to merge both and see if there s a conflict.  There seem to be too many changes to compare by inspection.

**Comment by rubberduck203** [comment]
I'm not the maintainer, or I'd try it. I could submit this PR to your fork & see though.

**Comment by ChrisNelsonPE** [comment]
> I'm not the maintainer, or I'd try it. I could submit this PR to your fork
> & see though.
> 
> I'll try the merge if you do.​

**Comment by fwsmaster** [comment]
New .gitignore file added to SP 2.4 alpha repository

**Comment by fwsmaster** [comment]
For technical reasons (software configuration management of SP branches), the pull request can not be merged with the SP main branche. The pull request will be closed.

**Pull request closed without merging**
